language: node_js
node_js:
  - "7"
before_install:
  - git config --global user.name "liujian10"
  - git config --global user.email "mapleliu1@gmail.com"
script:
  - npm run build
  - cd dist
  - git init
  - git add -A
  - git commit -m "Deploy GH"
  - git push -u https://$GH_TOKEN@github.com/liujian10/v-drawer.git HEAD:gh-pages --force
cache:
  directories:
    - node_modules